export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

// SPACE
export const SPACE_REQUEST = 'SPACE_REQUEST';
export const SPACE_SUCCESS = 'SPACE_SUCCESS';
export const SPACE_FAILURE = 'SPACE_FAILURE';
